### ISSUE TITLE
A lot of vis goodies!

### ISSUE THREAD

**Issue by ghost** [joshaw/dotfiles2#1]
I noticed that you had a lot of vis extensions, and that is great! :)

I just opened [this issue](https://github.com/martanne/vis/issues/331) on vis repo,  Would you be interested in a very simple, rather trivial plugin manager for vis?

**Comment by joshaw** [comment]
Sorry for not replying, I don't check github directly very often, but thanks for checking out my repo.

I'm not sure a plugin manager is the correct way to go. 
- Lua has the advantage over many scripting languages (ahem viml ahem) of being extremely fast to load and execute. This means "lazy-loading" should not ever be necessary.
- As far as I understand the intentions, vis is aimed at being small, efficient and compact. Plugins do not really fit that bill. The small utilities I have here are as much an investigation of my own into learning Lua.
- Lua already has the `require()` functionality to allow loading [modules](http://www.lua.org/manual/5.1/manual.html#pdf-module) which can be used from `visrc.lua` to implement a very satisfactory extension mechanism without extra thought.

That's just my thoughts. (BTW I don't use any plugins, builtin or external, when using [vim](https://github.com/joshaw/vim/blob/master/vimrc#L21-L35) either, so I may be biased)

**Comment by ghost** [comment]
Thank you for your "late" answer (not that much, and it is not a problem).

Vis seems to aim keeping a small code base.  Implementing the less essential or the specific features in lua could help keep it small, so that is why I thought in a way to organize plugins.

But now I agree it is not necessary, as lua already seems well structured enough to add any extra specific layer.  :)
